apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ruby-app.name" . }}-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "ruby-app.fullname" . }}
            port:
              number: {{ .Values.service.port }}