# Default values for ruby-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: registry.localhost:5000/ruby-app
  tag: "1.0"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

selectorLables:
  app-type: ruby-app

podAnnotations: {}
serviceAccount:
  create: true
  name: ruby-app-sa
podSecurityContext: {}

securityContext: {}

service:
  name: ruby-app-service
  type: ClusterIP
  port: 8080
  targetPort: 80

livenessProbe:
  httpGet:
    path: /healthcheck
    port: 80
  initialDelaySeconds: 10
readinessProbe:
  httpGet:
    path: /healthcheck
    port: 80
  initialDelaySeconds: 10

resources: 
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
